### PR TITLE
Fix: Quote path variables in shell scripts to handle space characters in directory paths

### LINKED ISSUE #641: Shell scripts fail when run from a directory with space characters in the directory path
### Component

Setup/Standup

### Describe the bug

This bug affects shell scripts used in standup, teardown, and run components. These shell scripts, in the `setup/` directory, fail silently if the directory path to these scripts contain space characters due to unquoted variable expansions.

Affected Files:
setup/e2e.sh
setup/env.sh
setup/functions.sh
setup/run.sh
setup/standup.sh
setup/teardown.sh
util/setup_precommit.sh

### Steps to reproduce

1. Clone the repository to a path containing spaces (e.g., `/home/vkn/My Projects/llm-d/llm-d-benchmark`)
2. Run `./setup/standup.sh -h`
3. Observe silent failure or errors like "sed: unterminated 's' command"

## Root Cause
   Unquoted path variables cause word splitting in bash when paths contain spaces. For example:
   - `pushd \`dirname "$(realpath $0)"\`` splits at each space
   - `source ${VAR}/file` fails when VAR contains spaces
   - Sed expressions with unquoted variables fail

## Impact
   - Scripts exit silently without error messages
   - Users in environments with spaces in paths cannot use the tools
   - Affects: All shell scripts listed above

## Solution
   Quote all variable expansions and command substitutions throughout shell scripts.

### PR DESCRIPTION
**Pull request by vknaik**
Fixes #641 

## Problem:
Scripts fail when run from directories containing spaces in their path due to unquoted variables causing word splitting.

## Solution:
- Quoted all path variables in setup/*.sh scripts (6 files)
- Quoted path variables in util/setup_precommit.sh
- Ensure proper handling of directory paths containing spaces

## Changes:
- **setup/**: e2e.sh, env.sh, functions.sh, run.sh, standup.sh, teardown.sh
- **util/**: setup_precommit.sh

## Testing:
Verified scripts can now run from directories with spaces in the path.

## Commits:
- fix: Quote path variables in shell scripts to handle spaces (setup/*.sh)
- fix: Quote path variables in setup/steps scripts and util/setup_precommit.sh

### CODE REVIEW

**Comment by vknaik** [comment]
@namasl You are correct. I will remove the .sh files under `setup/steps/` and resubmit the PR. Thx.

File: setup/run.sh [hunk 1]
```diff
@@ -444,18 +444,18 @@ for method in ${LLMDBENCH_DEPLOY_METHODS//,/ }; do
 
       for workload_type in ${LLMDBENCH_HARNESS_PROFILE_HARNESS_LIST}; do
         llmdbench_execute_cmd "${LLMDBENCH_CONTROL_KCMD} --namespace ${LLMDBENCH_HARNESS_NAMESPACE} delete configmap $workload_type-profiles --ignore-not-found" ${LLMDBENCH_CONTROL_DRY_RUN} ${LLMDBENCH_CONTROL_VERBOSE}
-        llmdbench_execute_cmd "${LLMDBENCH_CONTROL_KCMD} --namespace ${LLMDBENCH_HARNESS_NAMESPACE} create configmap $workload_type-profiles --from-file=${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}" ${LLMDBENCH_CONTROL_DRY_RUN} ${LLMDBENCH_CONTROL_VERBOSE}
+  llmdbench_execute_cmd "${LLMDBENCH_CONTROL_KCMD} --namespace ${LLMDBENCH_HARNESS_NAMESPACE} create configmap $workload_type-profiles --from-file=\"${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}\"" ${LLMDBENCH_CONTROL_DRY_RUN} ${LLMDBENCH_CONTROL_VERBOSE}
```
Comment (namasl) [inline setup/run.sh]: Not functional, but adding back spacing for clarity
```suggestion
        llmdbench_execute_cmd "${LLMDBENCH_CONTROL_KCMD} --namespace ${LLMDBENCH_HARNESS_NAMESPACE} create configmap $workload_type-profiles --from-file=\"${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}\"" ${LLMDBENCH_CONTROL_DRY_RUN} ${LLMDBENCH_CONTROL_VERBOSE}
```

File: setup/run.sh [hunk 2]
```diff
@@ -444,18 +444,18 @@ for method in ${LLMDBENCH_DEPLOY_METHODS//,/ }; do
...
       export LLMDBENCH_RUN_EXPERIMENT_ID_PREFIX=""
 
-      for treatment in $(ls ${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}/*.yaml); do
+for treatment in $(ls "${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}/"*.yaml); do
 
         export LLMDBENCH_RUN_EXPERIMENT_HARNESS_WORKLOAD_NAME=$(echo $treatment | rev | cut -d '/' -f 1 | rev)
         export LLMDBENCH_HARNESS_EXPERIMENT_PROFILE=$(echo $treatment | rev | cut -d '/' -f 1 | rev)
 
         tf=$(cat ${treatment} | grep "#treatment" | tail -1 | $LLMDBENCH_CONTROL_SCMD 's/^#//' || true)
-        if [[ -f ${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/${workload_type}/treatment_list/$tf ]]; then
```
Comment (namasl) [inline setup/run.sh]: ...spacing

File: setup/run.sh [hunk 3]
```diff
@@ -415,7 +415,7 @@ for method in ${LLMDBENCH_DEPLOY_METHODS//,/ }; do
         fi
       fi
 
-      rm -rf ${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/*
+rm -rf "${LLMDBENCH_CONTROL_WORK_DIR}/workload/profiles/"*
```
[the remark this answers is not in the document]
Comment (vknaik) [reply setup/run.sh]: Done and double checked for any remaining indentation issues.

**Comment by vknaik** [comment]
> > @namasl I have removed all the deprecated shell scripts files in `setup/steps/` directory and fixed and indentations in `setup/run.sh`. Please review again. Thx.
> 
> I still see the old shell scripts.

Sorry, I do not see any deprecated shell scripts in the HEAD of my fork. Where do you see those? I do see those on the `fix/paths_with_spaces`. They are not in my latest commit. Do I need to delete those on my branch as well?

**Comment by namasl** [comment]
> > > @namasl I have removed all the deprecated shell scripts files in `setup/steps/` directory and fixed and indentations in `setup/run.sh`. Please review again. Thx.
> > 
> > 
> > I still see the old shell scripts.
> 
> Sorry, I do not see any deprecated shell scripts in the HEAD of my fork. Where do you see those? I do see those on the `fix/paths_with_spaces`. They are not in my latest commit. Do I need to delete those on my branch as well?

Yes, they need to be removed from your `fix/paths-with-spaces` branch. You can see all the shell scripts here https://github.com/vknaik/llm-d-benchmark/tree/fix/paths-with-spaces/setup/steps

**Comment by vknaik** [comment]
> > > > @namasl I have removed all the deprecated shell scripts files in `setup/steps/` directory and fixed and indentations in `setup/run.sh`. Please review again. Thx.
> > > 
> > > 
> > > I still see the old shell scripts.
> > 
> > 
> > Sorry, I do not see any deprecated shell scripts in the HEAD of my fork. Where do you see those? I do see those on the `fix/paths_with_spaces`. They are not in my latest commit. Do I need to delete those on my branch as well?
> 
> Yes, they need to be removed from your `fix/paths-with-spaces` branch. You can see all the shell scripts here https://github.com/vknaik/llm-d-benchmark/tree/fix/paths-with-spaces/setup/steps

Thanks. I have deleted the script files from the branch `fix/paths-with-spaces` and verified they are gone and pushed the updates. Please review again.

**Review by namasl — APPROVED** [review]
